use_gpu: 1
seed_value: 41
gpu_idx: "0"
gpu_mem: 0.8
decom: 0
mat_key: "data"
channels: 64
global_min: 238.
global_max: 4095.
normalization: "global_normalization"
batch_size: 2
patch_size: 128
start_lr: 0.001
lr_update_factor: 0.1
lr_update_period: 250
train_data: "D:/jyu/jyu_indoor/only_low_psnrs_64_aligned/lowAligned/train"
eval_data: "D:/jyu/jyu_indoor/only_low_psnrs_64_aligned/lowAligned/test"
test_data: "D:/jyu/jyu_indoor/only_low_psnrs_64_aligned/lowAligned/test"
label_dir: "D:/jyu/jyu_indoor/only_low_psnrs_64_aligned/high/test"
phase: "train_and_test"
epoch: 400
eval_every_epoch: 200
plot_every_epoch: 50
c_loss_reconstruction: 10
c_loss_r_fidelity: 1
c_loss_i_smooth_low: 1
c_loss_i_smooth_delta: 2000
c_loss_fourier: 20
c_loss_spectral_cons: 1
alpha_i_smooth_low: 1
alpha_i_smooth_delta: 10
save_reflectance: true
save_illumination: true
save_i_delta: false