use_gpu: 1
seed_value: 41
gpu_idx: "0"
gpu_mem: 0.8
decom: 0
mat_key: "data"
channels: 64
global_min: 0.0708354
global_max: 1.6697606
normalization: "global_normalization"
batch_size: 1
patch_size: 128
start_lr: 0.001
lr_update_factor: 1
lr_update_period: 400
train_data: "./data/indoor/cross_validation/train_fold_1/low"
eval_data: "./data/indoor/cross_validation/eval_fold_1/low"
test_data: "./data/indoor/cross_validation/test_fold_1/low"
label_dir: "./data/indoor/cross_validation/test_fold_1/high"
phase: "train_and_test"
epoch: 400
eval_every_epoch: 200
plot_every_epoch: 200
c_loss_reconstruction: 10
c_loss_r_fidelity: 1
c_loss_i_smooth_low: 1
c_loss_i_smooth_delta: 20
c_loss_fourier: 0.2
c_loss_spectral_cons: 1
alpha_i_smooth_low: 1
alpha_i_smooth_delta: 10
save_reflectance: true
save_illumination: true
save_i_delta: true