use_gpu: 1
seed_value: 41
gpu_idx: "0"
gpu_mem: 0.8
decom: 0
mat_key: "data"
channels: 64
global_min: 0.0708354
global_max: 1.6697606
normalization: "global_normalization"
batch_size: 1
patch_size: 128
start_lr: 0.001
train_data: "../PairLIE/data/hsi_dataset_indoor_only/train"
eval_data: "../PairLIE/data/hsi_dataset_indoor_only/eval"
test_data: "../PairLIE/data/hsi_dataset_indoor_only/test"
label_dir: "../PairLIE/data/label_ll"
phase: "train_and_test"
epoch: 400
eval_every_epoch: 100
plot_every_epoch: 100
coeff_recon_loss_low: 10
coeff_Ismooth_loss_low: 1
coeff_recon_loss_low_eq: 1
coeff_R_low_loss_smooth: 1
coeff_relight_loss: 0.2
coeff_Ismooth_loss_delta: 20
coeff_fourier_loss: 0.2
coeff_spectral_loss: 1